language: python

python:
    - 2.7

# command to install dependencies
install:
   - pip install -r requirements.txt
   - pip install coverage coveralls --use-mirrors

# command to run tests
script:
    - nosetests --with-coverage --cover-erase --cover-package='.'

after_success:
    - coveralls
